name: Samsara Data Sync

on:
  schedule:
    # Runs at 00:15, 03:30, 06:45, 10:00, 13:15, 16:30, 19:45 UTC (7 times a day)
    - cron: '15 0 * * *'
    - cron: '30 3 * * *'
    - cron: '45 6 * * *'
    - cron: '0 10 * * *'
    - cron: '15 13 * * *'
    - cron: '30 16 * * *'
    - cron: '45 19 * * *'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Samsara data sync script
      env:
        api_key_samsara: ${{ secrets.api_key_samsara }}
        Samsara.json: ${{ secrets.SAMSARA_JSON }}
      run: python Samsara.py
