name: Samsara Data Sync

on:
  schedule:
    # Runs at 00:00, 03:00, 06:00, 09:00, 12:00, 15:00, 18:00 UTC (7 times a day)
    - cron: '0 0,3,6,9,12,15,18 * * *'
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Samsara data sync script
      env:
        api_key_samsara: ${{ secrets.api_key_samsara }}
        Samsara.json: ${{ secrets.SAMSARA_JSON }}
      run: python Samsara.py
