name: Run Jupyter Notebook with Papermill

on:
  schedule:
    - cron: '*/5 * * * *'   # Runs every 5 minutes (UTC)
  workflow_dispatch:        # Allows manual trigger
  push:
    branches:
      - main

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ipykernel jupyter papermill

    - name: Set up Jupyter kernel
      run: |
        python -m ipykernel install --user --name=python3

    - name: Debug: List available kernels
      run: jupyter kernelspec list

    - name: Run Papermill notebook
      run: |
        papermill Ontaria_motive.ipynb output_notebook.ipynb
