name: Schedule Python Script Run

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      # Step 4: Execute the Python script
      - name: Run Python Script
        run: |
          python ontario.py
