name: Schedule Notebook Run

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies, including papermill
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt
          pip install papermill

      # Step 4: Execute the Jupyter Notebook using Papermill
      - name: Run Jupyter Notebook
        run: |
          papermill your_notebook.ipynb output_notebook.ipynb
