name: Schedule Notebook Run

on:
  schedule:
    - cron: "*/5 * * * *"  # Runs every 5 minutes
  workflow_dispatch:       # Allows manual triggering from the Actions tab

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install papermill

      # Step 4: Run the Jupyter notebook using Papermill
      - name: Run Ontaria_motive Notebook
        run: |
          papermill Ontaria_motive.ipynb output_notebook.ipynb
